spring:
  application:
    name: website
  datasource:
    url: ${DB_URL}
    username: ${DB_NM}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET time_zone = 'Asia/Seoul';
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: Asia/Seoul
  config:
    import: optional:dotenv:.env
  task: 
    scheduling:
      time-zone: Asia/Seoul

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.silkroadpartnership: DEBUG

push:
  vapid:
    public-key: ${PUB_KEY}
    private-key: ${PRV_KEY}
    subject: "mailto:wnsdud412@naver.com"
  
gsheet:
 spreadsheetId: ${SHEET_ID}

server:
  port: 8081